FROM registry.svc.ci.openshift.org/openshift/origin-v4.0:cli
COPY --from=builder /go/src/github.com/openshift/must-gather/collection-scripts/* /usr/bin/

FROM quay.io/openshift/origin-must-gather:4.14.0 as builder

FROM quay.io/centos/centos:stream8

# For gathering data from nodes
RUN dnf update -y && \
    dnf install util-linux rsync -y && \
    dnf clean all

COPY --from=builder /usr/bin/oc /usr/bin/oc

# Copy all collection scripts to /usr/bin
COPY collection-scripts/* /usr/bin/

ENTRYPOINT /usr/bin/gather-monitoring-metrics