{
 "title": "apiserver-troubleshoot",
 "time": { "from": "2021-07-11T12:25:54.641Z", "to": "2021-07-17T10:51:49.632Z" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(instance:node_memory_utilisation:ratio, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "instance:node_load1_per_cpu:ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "instance:node_load1_per_cpu:ratio{job=\"node-exporter\", instance=~\"$node.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "instance:node_memory_utilisation:ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio{job=\"node-exporter\", instance=~\"$node.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "disk_io_time_seconds:rate1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "instance_device:node_disk_io_time_seconds:rate1m{device!~\"dm.*\", instance=~\"$node.*\"}",
     "legendFormat": "{{ instance }}_{{ device }}"
    }
   ]
  },
  {
   "title": "disk_io_time_weighted_seconds:rate1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance_device:node_disk_io_time_weighted_seconds:rate1m{device!~\"dm.*\", instance=~\"$node.*\"}",
     "legendFormat": "{{ instance }}_{{ device }}"
    }
   ]
  },
  {
   "title": "topk(25, max(etcd_object_counts) by (resource))",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(25, max(etcd_object_counts) by (resource))"
    }
   ]
  },
  { "title": "container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "container_cpu_usage_seconds_total:sum_rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate",
     "legendFormat": "{{ namespace }}_{{ pod }}_{{ container }}"
    }
   ]
  },
  {
   "title": "container_memory_rss (node)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_rss{node=~\"$node.*\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "container_memory_rss (namespace)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_rss{node=~\"$node.*\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "container_memory_rss (pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_rss{node=~\"$node.*\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Container CPU cfs_throttled_periods_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{node=~\"$node.*\"}[5m])) by (container)\n",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "etcd/apiserver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "etcd_disk_wal_fsync p50",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=~\".*etcd.*\"}[5m]))",
     "legendFormat": "{{ pod }}_{{ le }}"
    }
   ]
  },
  {
   "title": "etcd_disk_wal_fsync_duration_seconds_bucket p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=~\".*etcd.*\"}[5m]))",
     "legendFormat": "{{ instance }}_{{ pod }}"
    }
   ]
  },
  {
   "title": "etcd_disk_backend_commit_duration_seconds_bucket p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(etcd_disk_backend_commit_duration_seconds_bucket{job=~\".*etcd.*\"}[5m]))",
     "legendFormat": "{{ instance }}_{{ pod }}"
    }
   ]
  },
  {
   "title": "apiserver_request_latencies_bucket p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(apiserver_request_latencies_bucket{}[5m]))",
     "legendFormat": "{{ instance }}_{{ pod }}_{{ resource }}_{{ scope }}_{{ verb }}"
    }
   ]
  },
  {
   "title": "increase(etcd_server_slow_apply_total[5m])",
   "type": "graph",
   "description": "\"The total number of slow apply requests (likely overloaded from slow disk).\"",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(etcd_server_slow_apply_total[5m])",
     "legendFormat": "{{ instance }}_{{ pod }}"
    }
   ]
  },
  {
   "title": "etcd_server_leader_changes_seen_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_server_leader_changes_seen_total",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "backend_defrag_duration_seconds_sum",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_disk_backend_defrag_duration_seconds_sum",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "backend_snapshot_duration_seconds_sum",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_disk_backend_snapshot_duration_seconds_sum[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "rate(etcd_disk_wal_write_bytes_total)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(etcd_disk_wal_write_bytes_total[5m])",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "apiserver watchers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "apiserver-watchers (instance_apiserver_group_kind_ns_svc)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(apiserver_watch_events_total[5m])",
     "legendFormat": "{{ instance }}_{{ apiserver}}_{{ group }}_{{kind}}_{{namespace}}_{{ service }}"
    }
   ]
  },
  {
   "title": "registered watchers (instance, apiserver, group, namespace, kind, service)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_registered_watchers) by (instance, apiserver, group, namespace, kind, service)",
     "legendFormat": "{{ instance }}_{{ apiserver }}_{{ group }}_{{ namespace }}_{{ kind }}_{{ service }}"
    }
   ]
  },
  {
   "title": "apiserver-watchers Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(apiserver_watch_events_total[5m]))"
    }
   ]
  },
  {
   "title": "apiserver-watchers (apiserver,kind,namespace,service)c)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(apiserver_watch_events_total[5m])) by (apiserver,kind,namespace,service)",
     "legendFormat": "{{ apiserver}}_{{kind}}_{{namespace}}_{{ service }}"
    }
   ]
  },
  {
   "title": "apiserver_request_total by (verb)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(apiserver_request_total[5m])) by (verb)"
    }
   ]
  },
  {
   "title": "apiserver_request_total (WATCH|POST)\"} by (resource,escope,group,verb)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(apiserver_request_total{verb=~\"(WATCH|POST)\"}[5m])) by(resource,escope,group,verb)"
    }
   ]
  },
  { "title": "apiserver/flow-control", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "apiserver_flowcontrol_current_executing_requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_flowcontrol_current_executing_requests) by (namespace, flowSchema, priorityLevel)"
    }
   ]
  },
  {
   "title": "apiserver_flowcontrol_current_inqueue_requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_flowcontrol_current_inqueue_requests) by (namespace, flowSchema, priorityLevel)"
    }
   ]
  },
  {
   "title": "dispatched_requests_total by (namespace, flowSchema, priorityLevel)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_flowcontrol_dispatched_requests_total[5m])) by (namespace, flowSchema, priorityLevel)"
    }
   ]
  },
  {
   "title": "sum() rate() priority_level_request_count_samples_sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_flowcontrol_priority_level_request_count_samples_sum[5m])) by (namespace, flowSchema, priorityLevel)"
    }
   ]
  },
  {
   "title": "priority_level_request_count_watermarks_sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_flowcontrol_priority_level_request_count_watermarks_sum) by (namespace, flowSchema, priorityLevel)"
    }
   ]
  },
  {
   "title": "read_vs_write_request_count_samples_sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_flowcontrol_read_vs_write_request_count_samples_sum[5m])) by (namespace, request_kind, phase)"
    }
   ]
  },
  {
   "title": "read_vs_write_request_count_watermarks_sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_flowcontrol_read_vs_write_request_count_watermarks_sum[5m])) by (namespace, mark, request_kind, phase)"
    }
   ]
  },
  {
   "title": "apiserver_flowcontrol_rejected_requests_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apiserver_flowcontrol_rejected_requests_total) by (namespace, priorityLevel, flowSchema)"
    }
   ]
  },
  {
   "title": "apiserver_flowcontrol_request_concurrency_limit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(apiserver_flowcontrol_request_concurrency_limit[5m])) by (namespace, priorityLevel, flowSchema)"
    }
   ]
  }
 ]
}