{
 "title": "apiserver-investigation",
 "time": { "from": "2021-04-08T00:10:21.745Z", "to": "2021-04-08T18:03:02.558Z" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(instance:node_memory_utilisation:ratio, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "instance:node_load1_per_cpu:ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "instance:node_load1_per_cpu:ratio{job=\"node-exporter\", instance=~\"$node.*\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "instance:node_num_cpu:sum{job=\"node-exporter\", instance=~\"$node.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "instance:node_memory_utilisation:ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio{job=\"node-exporter\", instance=~\"$node.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "disk_io_time_seconds:rate1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "instance_device:node_disk_io_time_seconds:rate1m{device!~\"dm.*\", instance=~\"$node.*\"}",
     "legendFormat": "{{ instance }}_{{ device }}"
    }
   ]
  },
  {
   "title": "disk_io_time_weighted_seconds:rate1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "instance_device:node_disk_io_time_weighted_seconds:rate1m{device!~\"dm.*\", instance=~\"$node.*\"}",
     "legendFormat": "{{ instance }}_{{ device }}"
    }
   ]
  },
  {
   "title": "topk(25, max(etcd_object_counts) by (resource))",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(25, max(etcd_object_counts) by (resource))"
    }
   ]
  },
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "container_memory_rss (node)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_rss{node=~\"$node.*\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "container_memory_rss (namespace)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_rss{node=~\"$node.*\"}) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "container_memory_rss (pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_rss{node=~\"$node.*\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Container CPU cfs_throttled_periods_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{node=~\"$node.*\"}[5m])) by (container)\n",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  { "title": "etcd/apiserver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "etcd_disk_sync",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(etcd_disk_wal_fsync_duration_seconds_bucket[5m])",
     "legendFormat": "{{ instance }}_{{ pod }}_{{ le }}"
    }
   ]
  },
  {
   "title": "etcd_disk_wal_fsync_duration_seconds_bucket p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(etcd_disk_wal_fsync_duration_seconds_bucket{job=~\".*etcd.*\"}[5m]))",
     "legendFormat": "{{ instance }}_{{ pod }}"
    }
   ]
  },
  {
   "title": "etcd_disk_backend_commit_duration_seconds_bucket p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(etcd_disk_backend_commit_duration_seconds_bucket{job=~\".*etcd.*\"}[5m]))",
     "legendFormat": "{{ instance }}_{{ pod }}"
    }
   ]
  },
  {
   "title": "apiserver_request_latencies_bucket p99",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(apiserver_request_latencies_bucket{}[5m]))",
     "legendFormat": "{{ instance }}_{{ pod }}_{{ resource }}_{{ scope }}_{{ verb }}"
    }
   ]
  },
  {
   "title": "apiserver-watchers Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(apiserver_watch_events_total[5m]))"
    }
   ]
  },
  {
   "title": "apiserver-watchers (apiserver,kind,namespace,service)c)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(apiserver_watch_events_total[5m])) by (apiserver,kind,namespace,service)",
     "legendFormat": "{{ apiserver}}_{{kind}}_{{namespace}}_{{ service }}"
    }
   ]
  },
  {
   "title": "apiserver_request_total by (verb)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(apiserver_request_total[5m])) by (verb)"
    }
   ]
  },
  {
   "title": "apiserver_request_total (WATCH|POST)\"} by (resource,escope,group,verb)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(apiserver_request_total{verb=~\"(WATCH|POST)\"}[5m])) by(resource,escope,group,verb)"
    }
   ]
  },
  {
   "title": "increase(etcd_server_slow_apply_total[5m])",
   "type": "graph",
   "description": "\"The total number of slow apply requests (likely overloaded from slow disk).\"",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(etcd_server_slow_apply_total[5m])",
     "legendFormat": "{{ instance }}_{{ pod }}"
    }
   ]
  },
  {
   "title": "apiserver watchers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "apiserver-watchers (instance_apiserver_group_kind_ns_svc)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(apiserver_watch_events_total[5m])",
       "legendFormat": "{{ instance }}_{{ apiserver}}_{{ group }}_{{kind}}_{{namespace}}_{{ service }}"
      }
     ]
    },
    {
     "title": "registered watchers (instance, apiserver, group, namespace, kind, service)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(apiserver_registered_watchers) by (instance, apiserver, group, namespace, kind, service)",
       "legendFormat": "{{ instance }}_{{ apiserver }}_{{ group }}_{{ namespace }}_{{ kind }}_{{ service }}"
      }
     ]
    }
   ]
  }
 ]
}