{
 "title": "prometheus-troubleshoot",
 "time": { "from": "2021-07-13T16:30:04.069Z", "to": "2021-07-17T01:06:51.515Z" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(instance:node_memory_utilisation:ratio, instance)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(grpc_server_handling_seconds_count_sum_container, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "instance:node_load1_per_cpu:ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "instance:node_load1_per_cpu:ratio{job=\"node-exporter\", instance=~\"$node.*\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "instance:node_num_cpu:sum{job=\"node-exporter\", instance=~\"$node.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "instance:node_memory_utilisation:ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio{job=\"node-exporter\", instance=~\"$node.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "container_cpu_usage_seconds_total:sum_rate (node, pod, container)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"openshift-monitoring\"}",
     "legendFormat": "{{ node }}_{{ pod }}_{{ container }}"
    }
   ]
  },
  {
   "title": "grpc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "grpc_server_handling_seconds_count_sum_container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grpc_server_handling_seconds_count_sum_container{namespace=~\"$namespace.*\"}",
       "legendFormat": "{{ namespace }}_{{ pod }}_{{ container }}"
      }
     ]
    },
    {
     "title": "grpc_client_handling_seconds_count_sum_container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "grpc_client_handling_seconds_count_sum_container{namespace=~\"$namespace.*\"}",
       "legendFormat": "{{ namespace }}_{{ pod }}"
      }
     ]
    },
    {
     "title": "grpc_client_handling_seconds_count_sum_container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "grpc_client_handling_seconds_count_sum_container{namespace=~\"$namespace.*\"}",
       "legendFormat": "{{ namespace }}_{{ pod }}"
      }
     ]
    },
    {
     "title": "grpc_server_msg_sent_total_sum_rate {{ container }}_{{ service }}_{{ endpoint }}_{{  grpc_method }}_{{ grpc_type }}",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grpc_server_msg_sent_total_sum_rate{namespace=~\"$namespace.*\"}",
       "legendFormat": "{{ namespace }}_{{ pod }}_{{ container }}_{{ service }}_{{ endpoint }}_{{  grpc_method }}_{{ grpc_type }}"
      }
     ]
    },
    {
     "title": "grpc_server_msg_sent_total_sum_rate {{ container }}_{{ service }}_{{ endpoint }}_{{  grpc_method }}_{{ grpc_type }}",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "grpc_server_msg_sent_total_sum_rate{namespace=~\"$namespace.*\"}",
       "legendFormat": "{{ namespace }}_{{ pod }}_{{ container }}_{{ service }}_{{ endpoint }}_{{  grpc_method }}_{{ grpc_type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "engine",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "prometheus_engine_queries by pod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(prometheus_engine_queries{namespace=~\"$namespace.*\"}) by (pod)",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "prometheus_engine_queries by container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(prometheus_engine_queries{namespace=~\"$namespace.*\"}) by (container)"
      }
     ]
    },
    {
     "title": "prometheus_engine_queries by container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(prometheus_engine_queries{namespace=~\"$namespace.*\"}) by (endpoint)"
      }
     ]
    }
   ]
  },
  { "title": "requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "prometheus_http_request_duration_seconds_count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_http_request_duration_seconds_count[5m])) by (pod, container, handler)",
     "legendFormat": "{{ pod }}_{{container}}_{{ handler}}"
    }
   ]
  },
  {
   "title": "prometheus_http_requests_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_http_requests_total[5m])) by (pod, container, handler)",
     "legendFormat": "{{ pod }}_{{container}}_{{ handler}}"
    }
   ]
  },
  {
   "title": "prometheus_engine_query_duration_seconds_sum",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_engine_query_duration_seconds_sum[5m])) by (pod, container)"
    }
   ]
  },
  {
   "title": "requests-old",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "prometheus_http_request_duration_seconds_count_sum_container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_http_request_duration_seconds_count_sum_container",
       "legendFormat": "{{ pod }}_{{container}}_{{ handler}}"
      }
     ]
    },
    {
     "title": "prometheus_http_requests_total_sum_pod",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_http_requests_total_sum_pod",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  { "title": "hpa", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "kube_hpa_status_condition by status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_hpa_status_condition) by (status)"
    }
   ]
  },
  {
   "title": "kube_hpa_status_current_replicas by (ns,hpa)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_hpa_status_current_replicas) by (namespace,hpa)"
    }
   ]
  },
  {
   "title": "kube_hpa_status_desired_replicas by (ns,hpa)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_hpa_status_desired_replicas) by (namespace,hpa)"
    }
   ]
  },
  {
   "title": "changes kube_hpa_status_desired_replicas ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(changes(kube_hpa_status_desired_replicas[5m]))"
    }
   ]
  },
  {
   "title": "changes kube_hpa_status_desired_replicas (ns/hpa) ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(changes(kube_hpa_status_desired_replicas [5m]))by(namespace,hpa)",
     "legendFormat": "{{ namespace }}/{{ hpa }}"
    }
   ]
  },
  {
   "title": "% changes kube_hpa_status_desired_replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((count(changes(kube_hpa_status_desired_replicas [5m]) > 0)) / count(kube_hpa_status_desired_replicas)) * 100",
     "legendFormat": "{{ namespace }}/{{ hpa }}"
    }
   ]
  },
  { "title": "kube", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "kubelet_running_pods by (node)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kubelet_running_pods) by (node)"
    }
   ]
  },
  {
   "title": "kubelet_running_pods by (k8s_role)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kubelet_running_pods{node=~\"lxmaster.*\"})",
     "legendFormat": "masters"
    },
    {
     "expr": "sum(kubelet_running_pods{node=~\"lxinfra.*\"})",
     "legendFormat": "infra"
    },
    {
     "expr": "sum(kubelet_running_pods{node=~\"lxworker.*\"})",
     "legendFormat": "worker"
    }
   ]
  },
  {
   "title": "kubelet_running_pods by (k8s_role=infra)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubelet_running_pods{node=~\"lxinfra.*\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "kube_state_metrics_watch_total by (resource)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kube_state_metrics_watch_total[5m])) by (resource)"
    }
   ]
  },
  {
   "title": "scheduler_pending_pods by (pod,queue)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(scheduler_pending_pods) by (pod,queue)"
    }
   ]
  },
  {
   "title": "scheduler_pod_scheduling_attempts_sum by (pod)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(scheduler_pod_scheduling_attempts_sum[5m])) by (pod)"
    }
   ]
  },
  {
   "title": "scheduler_queue_incoming_pods_total by (pod,queue)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(scheduler_queue_incoming_pods_total[5m])) by (pod,queue)"
    }
   ]
  },
  {
   "title": "kube_state_metrics_list_total by (resource)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kube_state_metrics_list_total[5m])) by (resource)"
    }
   ]
  }
 ]
}